### ISSUE TITLE
How should I adjust parameters?

### ISSUE THREAD

**Issue by github0013** [jjviscomi/kalman-filter#1]
![8ee0a6d602b311e001e0c2eedf8f7216](https://user-images.githubusercontent.com/809378/38848568-aee86b16-4242-11e8-9021-a8c175a19fbb.png)

I have a sensor taking the current temperature, and its accuracy is -0.8 .. 0.8°C.
There are these parameters to setup

- process_noise
- measurement_noise
- state_vector
- control_vector

, and I have no idea what these numbers should be for this sensor with the accuracy range (-0.8 .. 0.8°C).

I know this is not an issue, but I really appreciate you can explain how to come up with the parameters for a better result.

Thanks

**Comment by jjviscomi** [comment]
@github0013 ... The only thing you have to worry about in a constant system is the estimate of the noise levels, thats the process_noise and measurement_noise.

The process_noise describes how noisy your system internally is. In other words, how much noise can you expect from the system itself? As your system is constant we can set this to a (very) low value, try `0.01`.

The measurement noise; how much noise is caused by your measurements? Expect that your measurements will contain most of the noise, it makes sense to set this parameter to a higher number (especially in comparison to the process noise) in this case. A good place to start with your above data might be `0.3`. However in practice you adjust these numbers until you get the readout and accuracy you expect ... 

I hope this helps a bit.
